# docker-compose.yml

services:
  postgres:
    image: postgres:16
    container_name: my-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: monuser
      POSTGRES_PASSWORD: monpassword
      POSTGRES_DB: consulter_depenses

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local