name: Full CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend:
    uses: ./.github/workflows/backend-ci.yml

  frontend:
    uses: ./.github/workflows/frontend-ci.yml

