name: CI

on:
  release:

  issues:
    types: [ opened, edited, milestoned ]

  push:
    branches:
      - 'main'
      - 'releases/**'

  pull_request:
    types:
      - opened
    branches:
      - 'releases/**'


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - Development
    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy on Cloud
        run: echo Hello, world!
  dev:
    name: Development
    steps:
      - Run the developer
  test:
    name: Testing
    needs:
      - Build
      - Development
    steps:
      - Testing the application
